trigger:
  branches:
    include:
      - main

variables:
  acrName: aksacr2
  imageName: pkishoreweatherapp
  imageTag: '$(Build.BuildId)'
  repoPath: 'weather-app/manifests/deployment.yml'

stages:
- stage: BuildAndDeploy
  jobs:
  - job: BuildAndPushImage
    displayName: Build and Push Docker Image
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push Image to ACR
      inputs:
        command: buildAndPush
        containerRegistry: 'acr-aksacr2-connection'   # <- Make sure this exact name exists in DevOps
        repository: $(imageName)
        Dockerfile: Dockerfile
        tags: |
          $(imageTag)

    - script: |
        echo "Replacing image tag in manifest..."
        sed -i "s|$(acrName).azurecr.io/$(imageName):.*|$(acrName).azurecr.io/$(imageName):$(imageTag)|" $(repoPath)
      displayName: Update image tag in deployment manifest

    - script: |
        git config user.name "Azure DevOps"
        git config user.email "azuredevops@yourdomain.com"
        git add $(repoPath)
        git commit -m "CI: Update image tag to $(imageTag)"
        git push
      displayName: Commit and push changes
