apiVersion : apps/v1
kind: Deployment
metadata:
  name: pkishoreweatherapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pkishoreweatherapp
  template:
    metadata:
      labels:
        app: pkishoreweatherapp 
    spec:
      containers:
        - name: pkishoreweatherapp 
          image: aksacr2.azurecr.io/pkishoreweatherapp
          ports:
          - containerPort: 80